<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: 
Where input is provided to the neural network; the features and bias of the data.
### Hidden Layer: 
Where the neural network is actually implemented and the processing is done.
### Output Layer: 
Where the result of all that work is provided.
### Neuron: 
Where a calculation is done that is one part of the greater whole.
### Weight: 
Like the slope in a linear function; how much should we care about a specific feature.
### Activation Function: 
Determines how much signal (information) to pass onto the next node (step) in the network.
### Node Map: 
A graph that shows the basic process of a given neural network.
### Perceptron: 
The most basic neural network? Takes in however many features are given and provides a result based on that.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

Input is provided based on the number of features for the problem being considered. A bias is also given to the network as an additional input. These inputs are then weighted (randomly at first) by being multiplied by the given weight and then put through the activation function. Here they are checked for error, the weights are updated, and the process (epoch) happens again for however many times it was set to. After each epoch an output is made and passed back into the network if it's still running.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [18]:
import numpy as np
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')
df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_deriv(x):
    sx = sigmoid(x)
    return sx * (1 - sx)

In [57]:
inputs = []
for i in range(len(df)):
    inputs.append([df.iloc[i,0], df.iloc[i,1], 1])
inputs = np.array(inputs)
inputs

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [30]:
target_output = []
for i in range(len(df)):
    target_output.append([df.iloc[i,2]])
target_output = np.array(target_output)
target_output

array([[1],
       [1],
       [1],
       [0]])

In [67]:
# Random weights (bias)
weights = 2* np.random.random((3,1)) - 1
weights

array([[-0.87952478],
       [-0.17372304],
       [-0.14080298]])

In [59]:
# Calculate weighted sum
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[ 0.18540174],
       [-0.4218148 ],
       [ 0.06623458],
       [-0.54098197]])

In [60]:
# 1 training epoch to get initial predictions
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.54621812],
       [0.39608257],
       [0.51655259],
       [0.36795918]])

In [61]:
# Get error
error = target_output - activated_output
error

array([[ 0.45378188],
       [ 0.60391743],
       [ 0.48344741],
       [-0.36795918]])

In [62]:
sigmoid_deriv(weighted_sum)

array([[0.24786389],
       [0.23920117],
       [0.24972601],
       [0.23256522]])

In [63]:
# Magic of backprop
adjustments = error * sigmoid_deriv(weighted_sum)
adjustments

array([[ 0.11247614],
       [ 0.14445776],
       [ 0.12072939],
       [-0.08557451]])

### Run it MANY times

In [68]:
# Steps we've already done: 
# 1. Randomly Initialized Weights. Those are in memory as `weights`
# 2. We've already got inputs data & target_output

for iteration in range(5001):
    
    # Weighted sum
    weighted_sum = np.dot(inputs, weights)
    
    # Activated output
    activated_output = sigmoid(weighted_sum)
    
    # Error
    error = target_output - activated_output
    
    # Adjustments
    adjustments = error * sigmoid_deriv(activated_output)
    
    # Update weight
    weights += np.dot(inputs.T, adjustments)

    if (iteration % 500) == 0:
        print(f"Iteration #{iteration}")
        
        print("Weights after training")
        print(weights)

        print("Output after training")
        print(activated_output)
        
        print("="*25)

Iteration #0
Weights after training
[[-0.75630852]
 [-0.09282784]
 [ 0.24747417]]
Output after training
[[0.4648573 ]
 [0.26496356]
 [0.42201038]
 [0.23253524]]
Iteration #500
Weights after training
[[-5.84298127]
 [-5.84296991]
 [ 8.82796983]]
Output after training
[[0.99985259]
 [0.95180343]
 [0.95180395]
 [0.05437193]]
Iteration #1000
Weights after training
[[-7.21289511]
 [-7.21289472]
 [10.87508622]]
Output after training
[[0.99998102]
 [0.97494237]
 [0.97494238]
 [0.0279308 ]]
Iteration #1500
Weights after training
[[-8.02511404]
 [-8.02511399]
 [12.09084256]]
Output after training
[[0.99999438]
 [0.98312764]
 [0.98312764]
 [0.01873016]]
Iteration #2000
Weights after training
[[-8.60330807]
 [-8.60330806]
 [12.95685545]]
Output after training
[[0.99999764]
 [0.98729592]
 [0.98729592]
 [0.01407395]]
Iteration #2500
Weights after training
[[-9.05226556]
 [-9.05226556]
 [13.62952842]]
Output after training
[[0.99999879]
 [0.98981762]
 [0.98981762]
 [0.01126641]]
Iteration #3000
Weig

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [69]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [85]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

scaler = MinMaxScaler()
norm = Normalizer()

feats = list(diabetes)[:-1]

print(feats)

feat_df = diabetes[feats]
feat_df.head()

norm_array = norm.transform(feat_df)
norm_array

['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']


array([[0.03355237, 0.82762513, 0.40262844, ..., 0.18789327, 0.00350622,
        0.27960308],
       [0.008424  , 0.71604034, 0.55598426, ..., 0.22407851, 0.00295683,
        0.26114412],
       [0.04039768, 0.92409698, 0.32318146, ..., 0.11765825, 0.00339341,
        0.16159073],
       ...,
       [0.02691539, 0.65135243, 0.38758161, ..., 0.14103664, 0.00131885,
        0.16149234],
       [0.00665306, 0.83828547, 0.39918356, ..., 0.20025708, 0.00232192,
        0.31269379],
       [0.00791454, 0.73605211, 0.55401772, ..., 0.24060198, 0.00249308,
        0.18203439]])

In [108]:
norm_array.shape

(768, 8)

In [111]:
ones = np.ones((768,1))
#ones

In [113]:
X = np.hstack((norm_array, ones))
X.shape

(768, 9)

In [97]:
#target_df = diabetes['Outcome']
target_array = np.array(diabetes['Outcome'])
target_array

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [114]:
y = target_array

In [134]:
X.T.shape

(9, 768)

In [135]:
(2 * np.random.random((X.shape[1],1)) - 1).shape

(9, 1)

In [218]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 11):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = self.__sigmoid(x)
        return sx * (1-sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """
        y = y.reshape((y.shape[0],1))
        
        # Randomly Initialize Weights
        weights = 2 * np.random.random((X.shape[1],1)) - 1
        print(weights)

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, weights)

            # Activate!
            activated_output = self.__sigmoid(weighted_sum)
            print(f"Predictions after loop {i}: \n", activated_output[:5])
            print("="*20)

            # Calc error
            error = y - activated_output
#            print("Error: ", error[:10])

            # Update the Weights
            adjustments = error * self.__sigmoid_derivative(activated_output)
            weights += np.dot(X.T, adjustments)
        
#             if (i % 2) == 0:
#                 print(f"Iteration #{i}")

#                 print("Weights after training")
#                 print(weights)

#                 print("Output after training")
#                 print(activated_output[:10])

#                 print("="*25)
        
        return self


    def predict(self, X):
        """Return class label after unit step"""
        return activated_output

In [219]:
prediction = Perceptron().fit(X,y)

[[-0.6468957 ]
 [ 0.47111287]
 [ 0.71503598]
 [ 0.64281916]
 [-0.64339978]
 [ 0.4376066 ]
 [-0.12292621]
 [ 0.36580894]
 [-0.55870422]]
Predictions after loop 0: 
 [[0.60043481]
 [0.62737987]
 [0.54779989]
 [0.46409166]
 [0.40313948]]
Predictions after loop 1: 
 [[2.16518068e-25]
 [1.53230860e-25]
 [6.60686015e-25]
 [4.72273499e-24]
 [1.56024570e-22]]
Predictions after loop 2: 
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
Predictions after loop 3: 
 [[2.53012460e-51]
 [7.22768812e-52]
 [4.43174127e-50]
 [8.50028701e-50]
 [1.19132405e-46]]
Predictions after loop 4: 
 [[0.99624849]
 [0.9637371 ]
 [0.99938099]
 [0.99997542]
 [0.99999952]]
Predictions after loop 5: 
 [[1.16401723e-75]
 [1.58612801e-76]
 [9.07086564e-74]
 [4.83084216e-74]
 [2.00877021e-69]]
Predictions after loop 6: 
 [[1.22174159e-22]
 [5.83223359e-24]
 [3.30454140e-21]
 [2.31167065e-20]
 [3.49631677e-17]]
Predictions after loop 7: 
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
Predictions after loop 8: 
 [[1.42766766e-48]
 [2.75098407e-50]
 [2.2166

In [217]:
prediction.predict(X)[:10]

array([[0.20816008],
       [0.20129959],
       [0.21268791],
       [0.19363333],
       [0.21632943],
       [0.2103207 ],
       [0.20495601],
       [0.28968107],
       [0.22294085],
       [0.18273171]])

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?

In [137]:
weights = 2 * np.random.random((X.shape[1],1)) - 1
weights

array([[ 0.77877749],
       [-0.63054588],
       [-0.70452722],
       [-0.4348241 ],
       [-0.36045161],
       [ 0.96548652],
       [ 0.34849157],
       [-0.0807118 ],
       [-0.6316217 ]])

In [140]:
weighted_sum = np.dot(X, weights)
weighted_sum.shape

(768, 1)

In [141]:
activated_output = sigmoid(weighted_sum)
activated_output.shape

(768, 1)

In [150]:
error = y.reshape((y.shape[0],1)) - activated_output
error.shape

(768, 1)

In [147]:
y.shape

(768,)

In [159]:
adjustments = error * sigmoid_deriv(activated_output)
adjustments.shape

(768, 1)

In [162]:
weights += np.dot(X.T, adjustments)
weights

array([[ 3.02786018],
       [54.93544737],
       [21.94450496],
       [ 6.6622127 ],
       [29.15823382],
       [13.8312346 ],
       [ 0.56945234],
       [13.6481393 ],
       [78.30535319]])

In [216]:
y.reshape((y.shape[0],1))[:10]

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1]], dtype=int64)