<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Using TensorFlow Keras, Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn.

This is your "Hello World!" of TensorFlow.

### Example TensorFlow Starter Code

```python 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(3, activation='sigmoid', input_dim=2),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['acc'])

results = model.fit(X,y, epochs=100)

```

### Additional Written Tasks:
1. Investigate the various [loss functions](https://www.tensorflow.org/api_docs/python/tf/keras/losses). Which is best suited for the task at hand (predicting 1 / 0) and why? 
2. What is the difference between a loss function and a metric? Why might we need both in Keras? 
3. Investigate the various [optimizers](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers). Stochastic Gradient Descent (`sgd`) is not the learning algorithm dejour anyone. Why is that? What do newer optimizers such as `adam` have to offer? 

In [2]:
import numpy as np

In [47]:
x1 = np.array((0,0,1,0,1,1,0))
x2 = np.array((0,1,0,1,0,1,0))
x3 = np.array((1,1,1,0,0,1,0))
y = np.array((0,1,1,1,1,0,0))

X = np.column_stack((x1, x2, x3))
print(X.shape)

print(y.shape)
# y = y.T
# print(y.shape)

(7, 3)
(7,)


# One

In [45]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(3, activation='sigmoid', input_dim=3),
    Dense(4, activation='sigmoid'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['acc'])


In [48]:
results = model.fit(X,y, epochs=100)

Train on 7 samples
Epoch 1/100
7/7 [==============================] - 0s 721us/sample - loss: 0.6836 - acc: 0.5714
Epoch 2/100
7/7 [==============================] - 0s 285us/sample - loss: 0.6836 - acc: 0.5714
Epoch 3/100
7/7 [==============================] - 0s 285us/sample - loss: 0.6836 - acc: 0.5714
Epoch 4/100
7/7 [==============================] - 0s 285us/sample - loss: 0.6836 - acc: 0.5714
Epoch 5/100
7/7 [==============================] - 0s 428us/sample - loss: 0.6836 - acc: 0.5714
Epoch 6/100
7/7 [==============================] - 0s 427us/sample - loss: 0.6835 - acc: 0.5714
Epoch 7/100
7/7 [==============================] - 0s 423us/sample - loss: 0.6835 - acc: 0.5714
Epoch 8/100
7/7 [==============================] - 0s 285us/sample - loss: 0.6835 - acc: 0.5714
Epoch 9/100
7/7 [==============================] - 0s 423us/sample - loss: 0.6835 - acc: 0.5714
Epoch 10/100
7/7 [==============================] - 0s 285us/sample - loss: 0.6835 - acc: 0.5714
Epoch 11/100
7/7 [==

# Two

### Build a Tensor Keras Perceptron

Try to match the architecture we used on Monday - inputs nodes and one output node. Apply this architecture to the XOR-ish dataset above. 

After fitting your model answer these questions: 

Are you able to achieve the same results as a bigger architecture from the first part of the assignment? Why is this disparity the case? What properties of the XOR dataset would cause this disparity? 

Now extrapolate this behavior on a much larger dataset in terms of features. What kind of architecture decisions could we make to avoid the problems the XOR dataset presents at scale? 

*Note:* The bias term is baked in by default in the Dense layer.

In [49]:
model_2 = Sequential([
    Dense(3, activation='sigmoid', input_dim=3),
    Dense(1, activation='sigmoid')
])

model_2.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['acc'])

In [50]:
results_2 = model_2.fit(X,y, epochs=100)

Train on 7 samples
Epoch 1/100
7/7 [==============================] - 0s 24ms/sample - loss: 0.8616 - acc: 0.4286
Epoch 2/100
7/7 [==============================] - 0s 146us/sample - loss: 0.8600 - acc: 0.4286
Epoch 3/100
7/7 [==============================] - 0s 147us/sample - loss: 0.8585 - acc: 0.4286
Epoch 4/100
7/7 [==============================] - 0s 285us/sample - loss: 0.8570 - acc: 0.4286
Epoch 5/100
7/7 [==============================] - 0s 285us/sample - loss: 0.8555 - acc: 0.4286
Epoch 6/100
7/7 [==============================] - 0s 285us/sample - loss: 0.8540 - acc: 0.4286
Epoch 7/100
7/7 [==============================] - 0s 285us/sample - loss: 0.8525 - acc: 0.4286
Epoch 8/100
7/7 [==============================] - 0s 282us/sample - loss: 0.8510 - acc: 0.4286
Epoch 9/100
7/7 [==============================] - 0s 277us/sample - loss: 0.8495 - acc: 0.4286
Epoch 10/100
7/7 [==============================] - 0s 285us/sample - loss: 0.8481 - acc: 0.4286
Epoch 11/100
7/7 [===

### Below was an attempt at coding like yesterday.

In [22]:
X_2 = np.column_stack((x1, x2, x3))
print(X_2)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]


In [23]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [40]:
weights = 2 * np.random.random((3,1)) - 1
print(weights)
print(weights.shape)

[[ 0.90687437]
 [-0.19735172]
 [ 0.00922398]]
(3, 1)


In [28]:
weighted_sum = np.dot(X_2, weights)
print(weighted_sum)
print(weighted_sum.shape)

[[-0.10573588]
 [-0.56517933]
 [-0.18833496]
 [-0.45944345]
 [-0.08259908]
 [-0.64777841]
 [ 0.        ]]
(7, 1)


In [29]:
activated_output = sigmoid(weighted_sum)
print(activated_output)
print(activated_output.shape)

[[0.47359063]
 [0.36234991]
 [0.45305494]
 [0.38711786]
 [0.47936196]
 [0.34349034]
 [0.5       ]]
(7, 1)


In [32]:
error = y.reshape((y.shape[0],1)) - activated_output
print(error)
print(error.shape)

[[-0.47359063]
 [ 0.63765009]
 [ 0.54694506]
 [ 0.61288214]
 [ 0.52063804]
 [-0.34349034]
 [-0.5       ]]
(7, 1)


In [33]:
adjustments = error * sigmoid_derivative(weighted_sum)
print(adjustments)
print(adjustments.shape)

[[-0.11806735]
 [ 0.14733062]
 [ 0.13553089]
 [ 0.14541096]
 [ 0.12993775]
 [-0.0774587 ]
 [-0.125     ]]
(7, 1)


In [35]:
weights += np.dot(X_2.T, adjustments)
print(weights)
print(weights.shape)

[[ 0.10541087]
 [-0.24416057]
 [-0.01840043]]
(3, 1)


In [41]:
for iteration in range(10001):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(X_2, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Calc error
    error = y.reshape((y.shape[0],1)) - activated_output
    
    adjustments = error * sigmoid_derivative(activated_output)
    
    # Update the Weights
    weights += np.dot(X_2.T, adjustments)
    
    if (iteration % 1000) == 0:
        print(f"Iteration #{iteration}")
        
        print("Weights after training")
        print(weights)

        print("Output after training")
        print(activated_output)
        
        print("="*25)

Iteration #0
Weights after training
[[ 0.88299795]
 [-0.08729681]
 [-0.06619689]]
Output after training
[[0.50230598]
 [0.45310629]
 [0.71424645]
 [0.45082158]
 [0.71236014]
 [0.67233096]
 [0.5       ]]
Iteration #1000
Weights after training
[[ 1.14764484]
 [ 1.14764484]
 [-1.09483664]]
Output after training
[[0.2507086 ]
 [0.51319898]
 [0.51319898]
 [0.75908047]
 [0.75908047]
 [0.76860537]
 [0.5       ]]
Iteration #2000
Weights after training
[[ 1.14764484]
 [ 1.14764484]
 [-1.09483664]]
Output after training
[[0.2507086 ]
 [0.51319898]
 [0.51319898]
 [0.75908047]
 [0.75908047]
 [0.76860537]
 [0.5       ]]
Iteration #3000
Weights after training
[[ 1.14764484]
 [ 1.14764484]
 [-1.09483664]]
Output after training
[[0.2507086 ]
 [0.51319898]
 [0.51319898]
 [0.75908047]
 [0.75908047]
 [0.76860537]
 [0.5       ]]
Iteration #4000
Weights after training
[[ 1.14764484]
 [ 1.14764484]
 [-1.09483664]]
Output after training
[[0.2507086 ]
 [0.51319898]
 [0.51319898]
 [0.75908047]
 [0.75908047]
 [

# Three

## Try building/training a more complex MLP on a bigger dataset.

Use TensorFlow Keras & the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the canonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the Internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 array which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [51]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [52]:
# input image dimensions
img_rows, img_cols = 28, 28

In [53]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 2s 0us/step


In [54]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [55]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simplify the problem for now: Zero or all else.

In [56]:
import numpy as np

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [57]:
# A Nice Binary target for ya to work with
y_train

array([0., 1., 0., ..., 0., 0., 0.])

### Estimating Your `net

In [61]:
model = Sequential([
    Dense(3, activation='sigmoid', input_dim=784),
    Dense(100, activation='sigmoid'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['acc'])


In [62]:
results = model.fit(x_train,y_train, epochs=100)

Train on 60000 samples
Epoch 1/100
60000/60000 [==============================] - 2s 27us/sample - loss: 0.3259 - acc: 0.8988
Epoch 2/100
60000/60000 [==============================] - 1s 24us/sample - loss: 0.3215 - acc: 0.90131s - l
Epoch 3/100
60000/60000 [==============================] - 2s 26us/sample - loss: 0.3180 - acc: 0.90130s - loss: 0.3204 - acc - ETA: 0s - loss: 0.3190 - ac
Epoch 4/100
60000/60000 [==============================] - 2s 26us/sample - loss: 0.3056 - acc: 0.9013
Epoch 5/100
60000/60000 [==============================] - 2s 26us/sample - loss: 0.2755 - acc: 0.90131s -
Epoch 6/100
60000/60000 [==============================] - 2s 27us/sample - loss: 0.2180 - acc: 0.90131s -
Epoch 7/100
60000/60000 [==============================] - 2s 27us/sample - loss: 0.1453 - acc: 0.9379
Epoch 8/100
60000/60000 [==============================] - 2s 26us/sample - loss: 0.0940 - acc: 0.9835
Epoch 9/100
60000/60000 [==============================] - 2s 26us/sample - loss: 0.06

## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?